
- name: reload systemd configuration
  command: systemctl daemon-reload
  become: true

# Restart service and ensure it is enabled

- name: restart elasticsearch
  service: name={{instance_init_script | basename}} state=restarted enabled=yes
  become: true
  when:
    - es_restart_on_change
    - es_start_service
  register: es_restarted
