---
- name: Configure existing instances
  hosts: api_servers_master
  remote_user: ubuntu
  vars:
      node_version: "0.10.33"
      node_version_tag: "v0.10.33"
      node_prefix: "node-v{{node_version}}"
      node_tarball: "{{node_prefix}}.tar.gz"
      node_path: "/usr/local"
      production: true
      backend: true
      frontend: false
      defer: true
      staging: false
      db: false
      local_path: "/public/cardquiry/gcmgr"
      install_path: "/var/www/gcmanager"
      repo: "git@github.com:loganetherton/gcmgr.git"
      branch: "master"
      primary_node: false
      env: "NODE_ENV=production RUN_DEFER=true"
      cron: true
      socket: false
  roles:
    - system
    - {role: mongodb, become: true}
    - node
    - {role: git, become: true}
    - nginx
    - app
    - logrotate
    - cron
