---
- name: Configure existing instances
  hosts: api_servers
  remote_user: ubuntu
  vars:
      production: true
      backend: true
      frontend: false
      defer: true
      staging: false
      db: false
      local_path: "/public/cardquiry/gcmgr"
      install_path: "/var/www/gcmanager"
      repo: "git@github.com:loganetherton/gcmgr.git"
      branch: "master"
      primary_node: false
      env: "NODE_ENV=production"
      cron: false
      socket: false
  roles:
#    - system
#    - {role: mongodb, become: true}
#    - node
#    - {role: git, become: true}
#    - nginx
    - app
    - logrotate
