---

- hosts: app_servers
  remote_user: ubuntu
  # sudo can be called here, and will apply to all tasks
  become: true
  tasks:
    - name: Test connection
      # modules don't necessarily need any parameters passed to them
      ping:
      remote_user: ubuntu
      # or sudo can be called here
      become: true
      # You can sudo to another user after logging in like this
      # sudo_user: root

