<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Additional Compiled Classes
    |--------------------------------------------------------------------------
    |
    | Here you may specify additional classes to include in the compiled file
    | generated by the `artisan optimize` command. These should be classes
    | that are included on basically every request into the application.
    |
    */

    'files' => [
        realpath(__DIR__ . '/../app/Api/Support/AppServiceProvider.php'),
        realpath(__DIR__ . '/../app/Api/Support/RouteServiceProvider.php'),
        realpath(__DIR__ . '/../app/Support/ProjectServiceProvider.php'),
        realpath(__DIR__ . '/../app/IoC/ServiceProvider.php'),
        realpath(__DIR__ . '/../vendor/ascope/shared/Libraries/Kangaroo/ServiceProvider.php'),
        realpath(__DIR__ . '/../vendor/ascope/shared/Libraries/Permissions/ServiceProvider.php'),
        realpath(__DIR__ . '/../vendor/ascope/shared/Libraries/Verifier/ServiceProvider.php'),
        realpath(__DIR__ . '/../vendor/ascope/shared/Libraries/Processor/ServiceProvider.php'),
        realpath(__DIR__ . '/../app/DAL/Support/DoctrineServiceProvider.php'),
        realpath(__DIR__ . '/../app/Api/Support/BaseController.php'),
        realpath(__DIR__ . '/../app/Api/Support/BaseTransformer.php'),
        realpath(__DIR__ . '/../app/Api/Support/BaseProcessor.php')
    ],

    /*
    |--------------------------------------------------------------------------
    | Compiled File Providers
    |--------------------------------------------------------------------------
    |
    | Here you may list service providers which define a "compiles" function
    | that returns additional files that should be compiled, providing an
    | easy way to get common files from any packages you are utilizing.
    |
    */

    'providers' => [
        //
    ],

];
