---
- name: Configure existing instances
  hosts: prod_servers_backend
  remote_user: ubuntu
  vars:
      node_version: "0.10.33"
      node_version_tag: "v0.10.33"
      node_prefix: "node-v{{node_version}}"
      node_tarball: "{{node_prefix}}.tar.gz"
      node_path: "/usr/local"
      production: true
      backend: true
      frontend: false
      defer: false
      staging: false
      db: false
      local_path: "/public/server/instance"
      install_path: "/var/www/instance"
      repo: "git@github.com:*/*.git"
      branch: "master"
  roles:
    - system
    - {role: mongodb, become: true}
    - node
    - php
    - {role: git, become: true}
    - nginx
    - app
