---
- name: Configure ES Server
  hosts: es_servers_staging
  remote_user: ubuntu
  vars:
    es_api_basic_auth_username: "instance"
    es_api_basic_auth_password: "LN2SuWD9S4tDKQSztg2f2Cb3Md5TKHCsXTs4dzg8SYD8VXmHk6"
    es_instance_name: "instance"
    es_api_host: "0.0.0.0"
    es_config: {
      network.host: "0.0.0.0",
      transport.tcp.port: 9300
    }
    es_scripts: true
    es_heap_size: 2g
  roles:
    - elasticsearch
