---

- name: Check if swap exists
  stat: path=/mnt/swapfile
  register: swap_check

- name: Allocate swap file member (2GB)
  when: not swap_check.stat.exists
  shell: dd if=/dev/zero of=/mnt/swapfile bs=1M count=2048
  become: true

- name: Change ownership of swapfile
  become: true
  when: not swap_check.stat.exists
  shell: chown root:root /mnt/swapfile && chmod 600 /mnt/swapfile

- name: Make and flag as swap space
  become: true
  when: not swap_check.stat.exists
  shell: mkswap /mnt/swapfile && swapon /mnt/swapfile

- name: Add swap to fstab
  become: true
  lineinfile:
    dest: /etc/fstab
    regexp: /mnt/swapfile
    line: "/mnt/swapfile none swap sw 0 0"

- name: turn on swap
  become: true
  command: swapon -a
