---

- name: Install nginx
  become: true
  apt: name=nginx state=present update_cache=yes

- name: Get ec2 information
  action: ec2_facts
  register: instance_facts

- name: Replace nginx global config
  become: true
  template: src=nginx.conf dest=/etc/nginx/nginx.conf

- name: Replace nginx site config (api)
  become: true
  template: src=default.j2 dest=/etc/nginx/sites-available/default
  when: socket == False
  notify:
    - restart nginx

- name: Replace nginx site config (socket)
  become: true
  template: src=default-socket.j2 dest=/etc/nginx/sites-available/default
  when: socket == True
  notify:
    - restart nginx

- name: Replace nginx site config (staging)
  become: true
  template: src=default-staging.j2 dest=/etc/nginx/sites-available/default
  when: staging == True
  notify:
    - restart nginx
